### ISSUE TITLE
The link to docs is broken

### ISSUE THREAD

**Issue by maleksware** [melvinchia3636/YouTube-Scraping-API#1]
Hello! Recently discovered your project on PyPI and got interested in it, but couldn't open the docs - the link is (maybe) broken. Searching it in ReadTheDocs didn't get any result with valid links. Can you please check the link?

**Comment by melvinchia3636** [comment]
Appreciated for your report. The DNS system for the documentation seems to
have a little bit of problem. I'll let you know as soon as I fixed it.

**Comment by melvinchia3636** [comment]
The documentation has now been migrated to a new place: https://ytsa.thecodeblog.net
