### ISSUE TITLE
Suggestion: code reformatting

### ISSUE THREAD

**Issue by maleksware** [melvinchia3636/YouTube-Scraping-API#13]
I know that your code follows some rules of styling. But some of them are non-Pythonic, as I can judge from PEP8 docs. I think I can format and clean the code in July to make it better for readers, users and contributors. I won't make any changes that cover logic, connection and core features.

What do you think about that?

**Comment by maleksware** [comment]
And yep I forgot, maybe you can push the next release to PyPI? We have some downloads already, why not having the latest version available?

**Comment by melvinchia3636** [comment]
> I know that your code follows some rules of styling. But some of them are non-Pythonic, as I can judge from PEP8 docs. I think I can format and clean the code in July to make it better for readers, users and contributors. I won't make any changes that cover logic, connection and core features.
> 
> What do you think about that?

Sure! I'll be really grateful if you can help me with that.

**Comment by melvinchia3636** [comment]
> And yep I forgot, maybe you can push the next release to PyPI? We have some downloads already, why not having the latest version available?

v1.1.3 has been pushed to PyPI. You can check it out right here: https://pypi.org/project/youtube-scraping-api/

**Comment by maleksware** [comment]
Okay, thanks for your answer. I will start in July because I don't have access to my computer at the moment.

**Comment by melvinchia3636** [comment]
> Okay, thanks for your answer. I will start in July because I don't have access to my computer at the moment.

No problem. Take your time.
