### ISSUE TITLE
What is `builtin_called` for in Channel?

### ISSUE THREAD

**Issue by maleksware** [melvinchia3636/YouTube-Scraping-API#14]
In Channel class I see `builtin_called` that is also involved in a decorator `@custom_property`:

https://github.com/melvinchia3636/YouTube-Scraping-API/blob/43105d3ce515566af26290246cc18019357a8be2/src/youtube_scraping_api/parser/channel.py#L11

What is its purpose?

In any case this should be added to docs.

**Comment by maleksware** [comment]
And also in decorators.py you have the `inspect` module import. What does it do?

**Comment by melvinchia3636** [comment]
> And also in decorators.py you have the `inspect` module import. What does it do?

Most likely it's automatically imported by vscode for some reason. It's now been removed.

**Comment by melvinchia3636** [comment]
> In Channel class I see `builtin_called` that is also involved in a decorator `@custom_property`:
> 
> https://github.com/melvinchia3636/YouTube-Scraping-API/blob/43105d3ce515566af26290246cc18019357a8be2/src/youtube_scraping_api/parser/channel.py#L11
> 
> What is its purpose?
> 
> In any case this should be added to docs.

I'll add it to the docs soon. As the function name describes, it's define if the function is getting called by another function, not user.
