### ISSUE TITLE
'YoutubeAPI' object has no attribute 'Video'

### ISSUE THREAD

**Issue by dominicdev** [melvinchia3636/YouTube-Scraping-API#17]
trying to scrape multiple video.. but getting this 'YoutubeAPI' object has no attribute 'Video' inside a loop

**Comment by dominicdev** [comment]
update! change the doc to video not Video! its working now

**Comment by melvinchia3636** [comment]
Should be

 YoutubeAPI().video(video_id)

**Comment by melvinchia3636** [comment]
Cool, I'll update it ASAP.

**Comment by melvinchia3636** [comment]
Documentation changed.
