### ISSUE TITLE
Documentation must say project is no longer maintained

### ISSUE THREAD

**Issue by BenjaminPoole** [melvinchia3636/YouTube-Scraping-API#19]
You need to update the documentation to say that the project is no longer maintained and that the video download no longer works (subtitles still work fine though)

When I try to download the video I get an empty video file (0 Bytes). I suspect this is because YouTube have changed their end. Would be really great if you can fix this but if you don't because you are no longer maintaining then please say so in the docs (https://ytsa.thecodeblog.net/en/latest/index.html) so that others don't waste their time on functionality that no longer works

The captions download works great though,
Also linking the git repo to the docs would be a good idea

Thanks very much

**Comment by melvinchia3636** [comment]
Thanks for notifying.

The documentation site for this long forgotten project has been taken down once and for all.

Sorry for any inconvenience.
