### ISSUE TITLE
[Question] Why Channel doesn't have a feature to return all metadata?

### ISSUE THREAD

**Issue by maleksware** [melvinchia3636/YouTube-Scraping-API#3]
When using Channel, I sometimes need to extract its metadata in JSON/Dictionary format. I can access the data using `_metadata`:

```
channel = Channel("channel_id")
channel.parseData()
print(channel._metadata)
```

But that's not a "public" feature, as it involves an insecure attribute `_metadata`. Should I write a function that extracts all channel's metadata securely?

P.S. As I want to contribute to this project in the future, maybe we can talk in Discord or somewhere else, if you're interested.

**Comment by maleksware** [comment]
I will open a pull request with this feature after your answer.

**Comment by melvinchia3636** [comment]
> I will open a pull request with this feature after your answer.

Thanks a lot.

**Comment by maleksware** [comment]
PR is ready to be merged. Please update the docs as I don't have access to them.

**Comment by melvinchia3636** [comment]
Documentation has been updated.
https://ytsa.thecodeblog.net/en/latest/API%20reference.html#youtube_scraping_api.parser.channel.Channel.raw
