### ISSUE TITLE
Possible typo in decorators.py

### ISSUE THREAD

**Issue by maleksware** [melvinchia3636/YouTube-Scraping-API#4]
In decorators.py file, I see 

`if self._is_builtin_callled and f.__name__ in self._static_properties:`
(line 5)

Is there a typo in "called"? This may lead to some serious errors.

**Comment by melvinchia3636** [comment]
Appreciated for the issue report. I'll fix it up as soon as possible.

**Comment by melvinchia3636** [comment]
The typo has been corrected in the latest commit.
