### ISSUE TITLE
[Enhancement] [Question] Do you want to create a TODO list with all features that are needed?

### ISSUE THREAD

**Issue by maleksware** [melvinchia3636/YouTube-Scraping-API#6]
There are some todos in the code, but it's not easy to find them. Do you have a list with such features?

**Comment by melvinchia3636** [comment]
I'll create one soon. But feel free to add whatever features that you think it's suitable for the project.

**Comment by melvinchia3636** [comment]
https://ytsa.thecodeblog.net/en/latest/#todo
