### ISSUE TITLE
Code styling question

### ISSUE THREAD

**Issue by maleksware** [melvinchia3636/YouTube-Scraping-API#8]
What naming style are you using? There are methods and attributes with `camelCase` and `snake_case`. Mixing them can lead to errors and worse code quality. Is it done on purpose?

**Comment by melvinchia3636** [comment]
camelCase is for function, while snake_case is for properties, but I'm not sure if i miss typed some of them

**Comment by maleksware** [comment]
Closing as #15 fixed everything.
